name: TeamsPlus
version: ${version}
main: dev.badbird.teams.TeamsPlus
api-version: 1.17
softdepend:
  - AntiCombatLog
  - Vault
  - LuckPerms
  - CoreProtect
  - LunarClient-API
authors:
  - Badbird5907
description: Teams plugin
permissions:
  teamsplus:
    staff:
      disband:
        description: Disband a team
        default: false
